Dockerfile updated

diff --git a/ImageService/Dockerfile b/ImageService/Dockerfile
--- a/ImageService/Dockerfile
+++ b/ImageService/Dockerfile
@@ -1,9 +1,16 @@
-FROM eclipse-temurin:17-jre-alpine AS base
+FROM eclipse-temurin:17-jre-alpine
 RUN addgroup -S appgroup && adduser -S appuser -G appgroup
 WORKDIR /app
-COPY image-service.jar jar1.jar
-COPY target/image-service.jar jar2.jar
-RUN cp jar1.jar app.jar 2>/dev/null || cp jar2.jar app.jar
+COPY target/ ./from_target/
+COPY . ./from_root/
+RUN \
+  if [ -f from_root/image-service.jar ]; then \
+    cp from_root/image-service.jar app.jar; \
+  elif [ -f from_target/image-service.jar ]; then \
+    cp from_target/image-service.jar app.jar; \
+  else \
+    echo "JAR not found" && exit 1; \
+  fi
 USER root
 RUN apk update && apk add --no-cache curl
 USER appuser
